### ISSUE TITLE
Can't update after version 0.0.3

### ISSUE THREAD

**Issue by francamatheus** [gabriel-kozma/swift-mask-textfield#13]
I try to update the pod with Cocoapods, tried 0.0.5, 1.0, 1.1.0 and none of them worked 

[!] CocoaPods could not find compatible versions for pod "SwiftMaskTextfield":
  In Podfile:
    SwiftMaskTextfield (~> 1.1.0)

None of your spec sources contain a spec satisfying the dependency: `SwiftMaskTextfield (~> 1.1.0)`.

**Comment by gabriel-kozma** [comment]
fixed!

Sorry about that, had forgotten to push to pod trunk
