### ISSUE TITLE
Import and class with different names

### ISSUE THREAD

**Issue by thomasccpereira** [gabriel-kozma/swift-mask-textfield#2]
Hi,

Thank you for sharing your work, nice job.
A little detail: your class is named SwiftMaskText**F**ield, otherwise swift module is named SwiftMaskText**f**ield.

I don't know if this detail influences in selection of Class and Module, I did select class for TextField in IB and Xcode didn't select module. I lost a little time with It. 😅 

Cheers

**Comment by gabriel-kozma** [comment]
Fixed on the new version (:

The names are matching now!

Sorry about that, I didn't see it
