### ISSUE TITLE
Support for Swift 4.1 or greater

### ISSUE THREAD

**Issue by nneuberger1** [gabriel-kozma/swift-mask-textfield#6]
Is there a plan to support Swift 4.0 or greater?

It's possible if I have time that I create a pull request into this project and fix things, if needed.

**Comment by gabriel-kozma** [comment]
I'll add support to swift 4.0 over this week

If there's new features or fixes you wish to add, feel free to create a pull request

**Comment by gabriel-kozma** [comment]
Support is added, feel free to try it out and let me know if there are any issues
